create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  merchant_name text not null,
  title text not null,
  code text not null,
  discount_text text,
  minimum_spend numeric(12,2),
  start_at timestamptz,
  end_at timestamptz,
  terms_html text,
  source_url text,
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.promo_codes enable row level security;

drop policy if exists "Public can read published promo codes" on public.promo_codes;
create policy "Public can read published promo codes" on public.promo_codes for select using (status = 'published');

drop policy if exists "Authenticated users can manage promo codes" on public.promo_codes;
create policy "Authenticated users can manage promo codes" on public.promo_codes for all to authenticated using (true) with check (true);

grant select on public.promo_codes to anon;
grant all on public.promo_codes to authenticated;
grant usage, select on sequence public.promo_codes_id_seq to authenticated;

create or replace function public.set_promo_codes_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists promo_codes_updated_at on public.promo_codes;
create trigger promo_codes_updated_at before update on public.promo_codes for each row execute function public.set_promo_codes_updated_at();