-- NAPS Supabase schema v1
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'editor' check (role in ('super_admin','admin','editor','merchant')),
  created_at timestamptz not null default now()
);

create or replace function public.is_naps_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('super_admin','admin','editor'));
$$;

create table if not exists public.states (
  id bigint generated by default as identity primary key,
  name text unique not null,
  type text not null check (type in ('state','federal_territory')),
  slug text unique not null
);

insert into public.states (name,type,slug) values
('Johor','state','johor'),('Kedah','state','kedah'),('Kelantan','state','kelantan'),
('Melaka','state','melaka'),('Negeri Sembilan','state','negeri-sembilan'),('Pahang','state','pahang'),
('Penang','state','penang'),('Perak','state','perak'),('Perlis','state','perlis'),
('Sabah','state','sabah'),('Sarawak','state','sarawak'),('Selangor','state','selangor'),
('Terengganu','state','terengganu'),('Kuala Lumpur','federal_territory','kuala-lumpur'),
('Labuan','federal_territory','labuan'),('Putrajaya','federal_territory','putrajaya')
on conflict (name) do nothing;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null, slug text unique not null, icon text, active boolean not null default true
);
create table if not exists public.merchants (
  id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null,
  merchant_type text, logo_url text, website_url text, active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(), merchant_id uuid not null references public.merchants(id) on delete cascade,
  state_id bigint references public.states(id), name text not null, address text, city text,
  latitude numeric(10,7), longitude numeric(10,7), active boolean not null default true
);
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(), category_id bigint references public.categories(id),
  name text not null, slug text unique not null, brand text, size_label text, barcode text,
  image_url text, description text, active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.product_prices (
  id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade,
  merchant_id uuid not null references public.merchants(id) on delete cascade, branch_id uuid references public.branches(id) on delete set null,
  state_id bigint references public.states(id), normal_price numeric(12,2), offer_price numeric(12,2) not null,
  offer_start timestamptz, offer_end timestamptz, source_url text, verified boolean not null default false,
  active boolean not null default true, updated_at timestamptz not null default now()
);
create index if not exists product_prices_product_idx on public.product_prices(product_id);
create index if not exists product_prices_state_idx on public.product_prices(state_id);
create index if not exists product_prices_offer_idx on public.product_prices(offer_price);

create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(), merchant_id uuid references public.merchants(id), category_id bigint references public.categories(id),
  state_id bigint references public.states(id), title text not null, slug text unique not null, description text, image_url text,
  discount_text text, start_at timestamptz, end_at timestamptz, source_url text, published boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.gold_rates (
  id uuid primary key default gen_random_uuid(), rate_date date not null, purity text not null,
  price_per_gram numeric(12,2) not null, merchant_name text, source_url text, created_at timestamptz not null default now()
);
create table if not exists public.remittance_rates (
  id uuid primary key default gen_random_uuid(), provider text not null, destination_country text not null,
  currency text not null, rate numeric(16,6) not null, transfer_fee numeric(12,2) default 0,
  payout_method text, source_url text, updated_at timestamptz not null default now()
);
create table if not exists public.fuel_prices (
  id uuid primary key default gen_random_uuid(), fuel_type text not null, price_per_litre numeric(8,3) not null,
  effective_from date not null, effective_to date, region text default 'Malaysia', source_url text,
  created_at timestamptz not null default now()
);
create table if not exists public.hospitals (
  id uuid primary key default gen_random_uuid(), name text not null, state_id bigint references public.states(id), city text,
  specialties text[], consultation_min numeric(12,2), consultation_max numeric(12,2), emergency_24h boolean default false,
  international_patient boolean default false, website_url text, active boolean not null default true
);
create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null,
  article_type text not null default 'how-to', excerpt text, content text, cover_url text,
  state_id bigint references public.states(id), published boolean not null default false,
  published_at timestamptz, created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.states enable row level security;
alter table public.categories enable row level security;
alter table public.merchants enable row level security;
alter table public.branches enable row level security;
alter table public.products enable row level security;
alter table public.product_prices enable row level security;
alter table public.deals enable row level security;
alter table public.gold_rates enable row level security;
alter table public.remittance_rates enable row level security;
alter table public.fuel_prices enable row level security;
alter table public.hospitals enable row level security;
alter table public.articles enable row level security;

do $$ declare t text; begin
  foreach t in array array['states','categories','merchants','branches','products','product_prices','deals','gold_rates','remittance_rates','fuel_prices','hospitals','articles'] loop
    execute format('drop policy if exists "public read %s" on public.%I', t, t);
    execute format('create policy "public read %s" on public.%I for select to anon, authenticated using (true)', t, t);
  end loop;
end $$;

do $$ declare t text; begin
  foreach t in array array['states','categories','merchants','branches','products','product_prices','deals','gold_rates','remittance_rates','fuel_prices','hospitals','articles'] loop
    execute format('drop policy if exists "admin write %s" on public.%I', t, t);
    execute format('create policy "admin write %s" on public.%I for all to authenticated using ((select public.is_naps_admin())) with check ((select public.is_naps_admin()))', t, t);
  end loop;
end $$;

drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select to authenticated
using ((select auth.uid()) = id or (select public.is_naps_admin()));

insert into public.categories(name,slug,icon) values
('Shop','shop','🛍️'),('Restaurant','restaurant','🍽️'),('Grocery','grocery','🛒'),
('Electronics','electronics','💻'),('Sports','sports','👟'),('Movie','movie','🎬'),
('Fair','fair','🎪'),('Campaign','campaign','📣'),('Event','event','🎟️'),
('Exhibition','exhibition','🏢'),('Opportunity','opportunity','🚀'),('Promo','promo','🎫')
on conflict (name) do nothing;

-- After creating your first Supabase Auth user, promote it manually:
-- insert into public.profiles(id, full_name, role)
-- values ('YOUR_AUTH_USER_UUID','Your Name','super_admin')
-- on conflict (id) do update set role='super_admin';
